# Research Question
Can machine learning models predict the financial risk of Turkish publicly traded companies using financial ratios?

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("financial_data.csv")

In [7]:
df.columns

Index(['Şirket Adı', 'Şirketin Kodu', 'Periyot', 'Yıl', 'Dönen Varlıklar',
       'Duran Varlıklar', 'Toplam Varlıklar', 'Kısa Vadeli Yükümlülükler',
       'Uzun Vadeli Yükümlülükler', 'Toplam Yükümlülükler',
       'Toplam Özkaynaklar', 'Ana Ortaklığa Ait Özkaynaklar',
       'Kontrol Gücü Olmayan Kaynaklar', 'Toplam Kaynaklar', 'Cari Oran',
       'Dönen Varlıklar / Aktif (%)', 'Asit Test Oranı', 'Nakit Oranı',
       'Aktif Karlılık (%)', 'Faaliyet Kar Marjı', 'Esas Faaliyet Kar Marjı',
       'Brüt Kar Marjı (%)', 'FAVÖK Marjı (%)', 'Net Kar Marjı',
       'Özsermaye Karlılığı (%)', 'VAFÖK Marjı', 'ROCE Oranı',
       'Finansman Gider / Net Satış', 'Borç Kaynak Oranı',
       'Duran Varlıklar / Aktif ', 'Duran Varlıklar / Maddi Özkaynak',
       'Esas Faaliyet Karı / Kısa Vadeli Borç', 'FAVÖK / Kısa Vade Borç',
       'Net Borç / FAVÖK', 'Kısa Vade Borç / Aktif',
       'Kısa Vade Borç / Dönen Varlık', 'Kısa Vade Borç / Özsermaye',
       'Kısa Vade Borç / Toplam Borç', 'Net Satışlar / Kısa Vade Borç',
       'Özsermaye / Aktif', 'Özsermaye / Maddi Duran Varlıklar',
       'Toplam Borç / Özsermaye', 'Aktif Devir Hızı', 'Alacak Devir Hızı',
       'Dönen Varlıklar Devir Hızı', 'Ticari Borçlar Devir Hızı',
       'Finansal Kaldıraç', 'Stok Devir Hızı', 'Altman Z-Skoru',
       'Springate Skoru', 'Zmijewski Skoru', 'L Model Skoru', 'Görüs Tipi'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27298 entries, 0 to 27297
Data columns (total 53 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Şirket Adı                             27298 non-null  object
 1   Şirketin Kodu                          27298 non-null  object
 2   Periyot                                27298 non-null  object
 3   Yıl                                    27298 non-null  int64
 4   Dönen Varlıklar                        27298 non-null  float64
 5   Duran Varlıklar                        27298 non-null  float64
 6   Toplam Varlıklar                       27298 non-null  float64
 7   Kısa Vadeli Yükümlülükler              27298 non-null  float64
 8   Uzun Vadeli Yükümlülükler              27298 non-null  float64
 9   Toplam Yükümlülükler                   27298 non-null  float64
 10  Toplam Özkaynaklar                     27298 non-null  float64
 11  Ana Ortaklığa Ait Özkaynaklar          27298 non-null  float64
 12  Kontrol Gücü Olmayan Kaynaklar         27298 non-null  float64
 13  Toplam Kaynaklar                       27298 non-null  float64
 14  Cari Oran                              27298 non-null  float64
 15  Dönen Varlıklar / Aktif (%)            27298 non-null  float64
 16  Asit Test Oranı                        27298 non-null  float64
 17  Nakit Oranı                            27298 non-null  float64
 18  Aktif Karlılık (%)                     27298 non-null  float64
 19  Faaliyet Kar Marjı                     27298 non-null  float64
 20  Esas Faaliyet Kar Marjı                27298 non-null  float64
 21  Brüt Kar Marjı (%)                     27298 non-null  float64
 22  FAVÖK Marjı (%)                        27298 non-null  float64
 23  Net Kar Marjı                          27298 non-null  float64
 24  Özsermaye Karlılığı (%)                27298 non-null  float64
 25  VAFÖK Marjı                            27298 non-null  float64
 26  ROCE Oranı                             27298 non-null  float64
 27  Finansman Gider / Net Satış            27298 non-null  float64
 28  Borç Kaynak Oranı                      27298 non-null  float64
 29  Duran Varlıklar / Aktif                27298 non-null  float64
 30  Duran Varlıklar / Maddi Özkaynak       27298 non-null  float64
 31  Esas Faaliyet Karı / Kısa Vadeli Borç  27298 non-null  float64
 32  FAVÖK / Kısa Vade Borç                 27298 non-null  float64
 33  Net Borç / FAVÖK                       27298 non-null  float64
 34  Kısa Vade Borç / Aktif                 27298 non-null  float64
 35  Kısa Vade Borç / Dönen Varlık          27298 non-null  float64
 36  Kısa Vade Borç / Özsermaye             27298 non-null  float64
 37  Kısa Vade Borç / Toplam Borç           27298 non-null  float64
 38  Net Satışlar / Kısa Vade Borç          27298 non-null  float64
 39  Özsermaye / Aktif                      27298 non-null  float64
 40  Özsermaye / Maddi Duran Varlıklar      27298 non-null  float64
 41  Toplam Borç / Özsermaye                27298 non-null  float64
 42  Aktif Devir Hızı                       27298 non-null  float64
 43  Alacak Devir Hızı                      27298 non-null  float64
 44  Dönen Varlıklar Devir Hızı             27298 non-null  float64
 45  Ticari Borçlar Devir Hızı              27298 non-null  float64
 46  Finansal Kaldıraç                      27298 non-null  float64
 47  Stok Devir Hızı                        27298 non-null  float64
 48  Altman Z-Skoru                         27298 non-null  float64
 49  Springate Skoru                        27298 non-null  float64
 50  Zmijewski Skoru                        27298 non-null  float64
 51  L Model Skoru                          27298 non-null  float64
 52  Görüs Tipi                             10751 non-null  object
dtypes: float64(48), int64(1), object(4)
memory usage: 11.0+ MB

In [14]:
df["Görüs Tipi"].unique()

array(['Şartlı', nan, 'Olumlu', 'Görüş bildirmekten kaçınma', 'Olumsuz'],
      dtype=object)

In [17]:
df.head()

,Şirket Adı,Şirketin Kodu,Periyot,Yıl,Dönen Varlıklar,Duran Varlıklar,Toplam Varlıklar,Kısa Vadeli Yükümlülükler,Uzun Vadeli Yükümlülükler,Toplam Yükümlülükler,...,Alacak Devir Hızı,Dönen Varlıklar Devir Hızı,Ticari Borçlar Devir Hızı,Finansal Kaldıraç,Stok Devir Hızı,Altman Z-Skoru,Springate Skoru,Zmijewski Skoru,L Model Skoru,Görüs Tipi
0,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,Yıllık,2020,452463975.0,15063837.0,467527812.0,325928352.0,2806817.0,328735169.0,...,8.438764,0.138862,24.189619,70.3135,0.0,8.4733,3.888765,-1.001948,-0.392849,Şartlı
1,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,9 Aylık,2020,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.000000,0.000000,0.000000,NaN
2,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,6 Aylık,2020,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.000000,0.000000,0.000000,Şartlı
3,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,6 Aylık,2020,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.000000,0.000000,0.000000,Olumlu
4,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,3 Aylık,2020,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0000,0.000000,0.000000,0.000000,NaN

In [20]:
#target -> Görüs Tipi

In [25]:
df["Görüs Tipi"].value_counts(dropna=False)

Görüs Tipi
NaN                           16547
Olumlu                         9610
Şartlı                         1054
Görüş bildirmekten kaçınma       81
Olumsuz                           6
Name: count, dtype: int64

In [27]:
df = df.dropna(subset=["Görüs Tipi"])

In [28]:
df["Görüs Tipi"].value_counts(dropna=False)

Görüs Tipi
Olumlu                        9610
Şartlı                        1054
Görüş bildirmekten kaçınma      81
Olumsuz                          6
Name: count, dtype: int64

# Values
Olumlu → 0 (Healthy)

Şartlı → 1 (Risk)

Olumsuz → 1 (Risk)

Görüş bildirmekten kaçınma → 1 (Risk)

In [29]:
df["risk"] = df["Görüs Tipi"].map({
    "Olumlu":0,
    "Şartlı":1,
    "Olumsuz":1,
    "Görüş bildirmekten kaçınma":1
})

C:\Users\bilal\AppData\Local\Temp\ipykernel_33000\3061077481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["risk"] = df["Görüs Tipi"].map({

In [30]:
df["risk"].value_counts()

risk
0    9610
1    1141
Name: count, dtype: int64

In [31]:
df.head()

,Şirket Adı,Şirketin Kodu,Periyot,Yıl,Dönen Varlıklar,Duran Varlıklar,Toplam Varlıklar,Kısa Vadeli Yükümlülükler,Uzun Vadeli Yükümlülükler,Toplam Yükümlülükler,...,Dönen Varlıklar Devir Hızı,Ticari Borçlar Devir Hızı,Finansal Kaldıraç,Stok Devir Hızı,Altman Z-Skoru,Springate Skoru,Zmijewski Skoru,L Model Skoru,Görüs Tipi,risk
0,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,Yıllık,2020,452463975.0,15063837.0,467527812.0,325928352.0,2806817.0,328735169.0,...,0.138862,24.189619,70.313500,0.0,8.473300,3.888765,-1.001948,-0.392849,Şartlı,1
2,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,6 Aylık,2020,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,Şartlı,1
3,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,6 Aylık,2020,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,Olumlu,0
5,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,Yıllık,2021,851508753.0,42045725.0,893554478.0,588233083.0,8695590.0,596928673.0,...,0.133382,18.501777,66.803837,0.0,8.642936,3.843520,-1.041097,-0.365671,Olumlu,0
7,A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.,A1CAP,6 Aylık,2021,557284135.0,37823261.0,595107396.0,355452425.0,4488809.0,359941234.0,...,0.189653,13.167611,60.483408,0.0,6.379480,2.762267,-1.209484,-0.358831,Olumlu,0

In [34]:
y=df["risk"]
X = df.drop(columns=["Görüs Tipi","risk"])

In [35]:
y.value_counts()

risk
0    9610
1    1141
Name: count, dtype: int64